### PR TITLE
[T-6476][15.0][ADD] l10n_es_facturae_custom_rounding: make l10n_es_facturae and account_invoice_custom_rounding modules compatible

### PR DESCRIPTION
**Pull request by manuelregidor**
@HaraldPanten 
@ValentinVinagre 
@luis-ron 

T-6476

### CODE REVIEW

**Comment by manuelregidor** [comment]
@Jesarregui Could you review, please? Thank you.

**Comment by HaraldPanten** [comment]
A better title (and the proper adaptation for the commit message) could be something like:

" [[T-6476][15.0][ADD] l10n_es_facturae_custom_rounding: make l10n_es_facturae and account_invoice_custom_rounding modules compatible."

Its reperesents more correctly the functionallity if the original modules al mentioned, as well.

**Comment by manuelregidor** [comment]
@HaraldPanten PR title and commit name changed

**Comment by HaraldPanten** [comment]
> @HaraldPanten PR title and commit name changed

Much better 👍

Let's wait for functional and technical reviews.

Once it's functionally validated, could you ask for a technical review to @Tisho99 ?

THX!

**Review by Jesarregui — APPROVED** [review]
Functional Review: LGTM
Selección_303

**Comment by Jesarregui** [comment]
@Tisho99 Could you do a technical review?

**Comment by manuelregidor** [comment]
@Tisho99 Could you review, please?

**Review by Tisho99 — APPROVED** [review]
LGTM. Code review

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Pull request merged**
